"""empty message

Revision ID: 10fd84657182
Revises: 
Create Date: 2023-09-25 20:20:21.888642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fd84657182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('question', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('tasks', 'text')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('tasks', sa.Column('text', sa.VARCHAR(), nullable=False))
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'question')
    # ### end Alembic commands ###
